name: gabarito_app
description: Aplicativo para correção de gabaritos - Hackathon 5º Período

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.9.0
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
#  # Assets para testes
#  assets:
#    - assets/images/

